application: gamealertbot-hrd
version: 2.1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: app.py

inbound_services:
- xmpp_message

